upgrade to latest dependencies (#668)
bumping golang.org/x/tools 05f9cb5...18332fe:
  > 18332fe go.mod: update golang.org/x dependencies
  > a5c4651 gopls/internal/protocol/command: fix struct field name in comment
  > 7d08a06 present, cmd/present, cmd/present2md: document lack of security hardening
  > e8a4348 refactor/satisfy: fix "the the" typo
  > 54624f9 internal/typesinternal: suppress jsonv2 warning
  > c117dde gopls/internal/golang: normalize instantiated fields before rename
  > b5b860c gopls/internal/mcp: report one-based reference line numbers
  > bf54bcd gopls/internal/golang/completion: avoid SEGV from double deslicing
  > 4b32d66 refactor/satisfy/find.go: fix panic on type errors
  > e6da7e4 gopls/internal/protocol/semtok: instructions for modifier/type changes
  > da22a7b gopls/internal/golang/definition: find the right unsafe
  > 952c3dc cmd/present: fix obsolete flag in security warning
  > 1f62bc8 present: validate background directive arguments
  > 3081d33 present: correct documented time for dates
  > 4e39c5f gopls/internal/test/integration/fake: integrate module cache
  > d5b12d7 gopls: add assembly DocumentHighlight, fix label scoping
  > 940d126 gopls/internal/analysis/fillswitch: add missing fmt import
  > f579934 go/analysis/passes/modernize: fix stditerators example
  > 63ec6f9 go/analysis/passes/modernize: add slicesclip analyzer
  > e46644d gopls/internal/golang/completion: handle aliased func types in literal completion
  > 95e150c go/analysis/passes/printf: stop reporting trailing newlines in Println
  > c2f2d83 go/types/typeutil: normalize instantiated callees
  > ff1f5ab gopls/test/completion: fix reported bug in collectCompletions
  > 56e88b2 gopls/internal/analysis/unusedfunc: use non-heuristic std check
  > 0ccfe93 go/analysis/passes/modernize: document 'go fix' command
  > 776a9a2 go/analysis/passes/fieldalignment: add more information to output
  > 55fcfca go/analysis/passes/modernize: fix stringsseq panic
  > 86ff45d gopls/test/completion: construct index explicitly
  > a3907ad go/loader: add concurrenc control
  > 1523a2a go/analysis/analysistest: enable sanity-checking of fact encoding
  > 6696fb1 go/types/internal/play: show Cursor path
  > b85ca07 internal/refactor/inline: make fact encoding deterministic
  > 1b7563a tools/go/analysis/passes/composite: fix test fail because flag.Flag new field
  > cc39f94 gopls/internal/analysis/fillswitch: support renamed package imports
  > 345e24c gopls/internal/cmd: use localhost:0 to avoid port race
  > 749de1f go/analysis/suite/vet: add sqlrowserr, scannererr analyzers
  > 4b383f6 internal/typesinternal: add TupleOf helper
  > ab304e8 gopls/internal/analysis/simplifycompositelit: preserve comments in fixes
  > 0f72b2d go/analysis/passes/modernize: fix analyzer URLs
  > b96d2a5 go/analysis/passes/modernize: slicesbackward - skip if s[i] is mutated
  > 23bbb39 go/analysis/unitchecker: correct cfg.Compiler comment
  > ae5216e go/analysis/unitchecker: fix unresolved import error message
  > 748ebaa gopls/internal/goasm: add Hover for assembly files
  > 9ae3407 internal/more{maps,slices}: promote from gopls
  > 5ef0154 gopls/test/integration/completion: Fix flaky test
  > a2c572e gopls/internal/cmd: set timeout for mcp server start
  > 33eb337 go/analysis/passes/modernize: use isScalarLvalue in stringscut modernizer
  > 1255efc gopls/internal/protocol: define enum string type for field kinds
  > fe90010 go/callgraph/rta: use typesinternal.ForEachElement
  > 3d67034 gopls/internal/analysis/simplifycompositelit: rewrite using types
  > cbdcbcc gopls/internal/golang: add Move Declaration skeleton
  > c566b29 gopls/internal/debug: show Package.Scope symbols
  > f7a8132 gopls/internal/golang: InlayHint: permit "ignore error" alternatives
  > b441908 gopls/internal/analysis/ptrtoerror: support type assert and instances
  > 591dfa6 gopls: run filecache validation asynchronously in the background
  > 7d18d5e gopls/internal/cmd: revamp CLI flag parsing
  > b2768f2 gopls/internal/cmd: fix Parent lineage strings on remote subcommands
  > a633660 gopls/internal/cmd: absorb tool package harness into cmd
  > df85682 gopls/internal/tool: rename Application to Command
  > 9825994 gopls/internal/cmd: group remote connection flags on Application
  > fcfa953 gopls/internal/analysis/ptrtoerror: detect inconsistent use of E/*E as error
  > b0dc4ae gopls/internal/completion: fix issue 80268
  > 816ec5a go/analysis/passes/modernize: skip WaitGroup.Go rewrite when defer can recover
  > c03c669 go/analysis/passes/stdversion: correctly format symbol names
  > 2b4da68 go/analysis/passes/modernize: avoid errorsastype panic on package variables
  > e227a53 gopls/internal/golang: fix crash in ExtractToNewFile
  > 6cbeeac internal/typesinternal: avoid linkname hacks
  > 3491921 gopls/doc/release: semtok ClientCapabilities change release notes
  > fc7339d go/analysis/passes/modernize: embedlit - skip if no selections are embedded
  > 95f84b6 gopls: respect client capabilities for semtok enabled tokens and mods
  > 620a92a go/analysis/passes/modernize: embedlit - skip multi assigns and decls
  > d568f18 gopls/internal/golang: freesymbols: use html/template
  > cd7d17b go/analysis/passes/modernize: add reflecttypeassert analyzer
  > 687891a gopls/doc/release/v0.23.0.md: remove "expected"
  > 8229bb0 gopls/go.mod: update dependencies following the v0.23.0 release

Signed-off-by: Knative Automation <automation@knative.team>